### ISSUE TITLE
[TODO] 배포 전 체크리스트

### ISSUE THREAD

**Issue by SeoSang** [Memo8-KoreaUniv/Kramo#8]
### 개요

배포 전 해야할 사소한 일들 체크리스트를 생각날 때마다 추가할 예정입니다.

- [x] `.env` 파일들 정리
- [ ] 디버깅용 코드 (예 : console.log) 정리
- [x] warnning 들 해결
- [ ] 모바일 화면에도 적합한지 테스트
- [x] api 문서 예시코드 정리
- [ ] Readme.md 정리
