### ISSUE TITLE
[Login] 네이버 아이디로 로그인

### ISSUE THREAD

**Issue by SeoSang** [Memo8-KoreaUniv/Kramo#9]
## 네이버 아이디로 로그인

![image](https://user-images.githubusercontent.com/28820058/119834478-f5eeac00-bf3a-11eb-9c22-f84eb8b26c8a.png)

네이버 아이디로 로그인, 줄여서 `네아로` 라고 부릅니다.
[네이버 Developers](https://developers.naver.com/main/) 에서 Kramo 이름으로 어플리케이션 등록하고
[네아로 개발 가이드](https://developers.naver.com/docs/login/devguide/devguide.md) 참고해서 구현해보았습니다.

1. `네이버 아이디로 로그인`  버튼을 누르게 되면, 네이버 로그인 연동 후 필요한 사항에 대해 동의를 구하게 됩니다.
  - 저희 서비스 같은 경우는 필요한 정보가 많지 않아, 필수 (이름, 닉네임, 휴대전화번호, 이메일), 선택(캘린더 및 나머지) 정도만 받도록 했습니다. 추가적인 정보가 필요하고 생각되면 논의하면 좋을 것 같습니다. 
2.  그 후 연동이 완료됐다면 리다이렉트되서 기본 화면으로 돌아오고, naverAccessToken을 받게됩니다. 
3.  리다이렉트 후, 저희 자체적인 api (POST `/api/user`)를 호출해서 몽고 DB에 접근하게 됩니다.
  - 해당 네이버id를 가진 도큐먼트가 존재한다면, 단순히 로그인 처리
  - 해당 네이버id를 가진 도큐먼트가 존재한지 않다면, 정보를 바탕으로 자동 create
4. 최종적으로 user 정보를 [JWT](https://jwt.io/) 를 이용해 토큰화 시켜서 (Kramo용 access token) set-cookie 시키고 res를 반환하게 됩니다. 로그인 완료 후에는 홈으로 이동됩니다.
  - 쿠키의 key값은 .env 파일에 의해 관리됩니다.
5. 추후에는 해당 토큰(Kramo용 access token) 을 이용해서 로그인여부를 판단하게 됩니다.

## 추후 논의사항

- 현재 네아로만으로 로그인하게끔 헀는데 저희 서비스만의 로그인이 따로 필요할지는 논의해 봐야할 것 같습니다.
(회원가입도 마찬가지입니다.)

## TODO

- [x] recoil 도입해서, 토큰값을 통해서 **유저 정보 로드** 받고 state에 담아두는 기능
- [x] 로컬 로그인 및 회원가입 (필요하다면)
- [x] 로그인 여부에 따라 메뉴 버튼 바꾸기

**Comment by gyunius** [comment]
발표 중 자체 로그인과 소셜 로그인(네이버, 카카오) 모드 구현하려는 조가 있었는데, 자체 로그인만으로도 굉장히 일이 많기 때문에 소셜 로그인을 먼저 구현하고 나중에 작업해서 실기능 구현에 좀더 시간을 들이라는 피드백이 있었습니다.
처음에 생각했던 것보다 중요하게 평가하는 기능도 아닌 것 같고, 날씨나 위치같이 작업해야 할 부분이 충분히 남은 것 같아서 가장 뒤로 미루거나 아예 목표에서 삭제해도 무방하다고 생각합니다.

**Comment by vwjdtjdwnsv** [comment]
저도 동의합니다. 자체 로그인 기능은 구현 난이도에 비해 크게 필요성이 느껴지진 않습니다. 우선 순위를 가장 마지막으로 하는 것이 좋을 것 같습니다.
